### ISSUE TITLE
Checklist for Review 3

### ISSUE THREAD

**Issue by blackstar3092** [blackstar3092/frostbyte_frontend#19]
- [x] Working Small Server API: Whole Team
- [x] Working Big Server: Abby
- [x] Working Big Server Integrated API (about page): Risha
- [x] Video Script: Ava
- [x] Video Recorded: Whole Team
- [x] Video Edited: Whole Team
- [x] New APIs: Gemini: Elliot
- [x] New APIs: Review Stars: Risha
- [ ] New APIs: Analytics: Shriya
- [x] Working post system for 4/4 national parks: Risha
- [ ] Working camping quiz save to backend: Aranya
- [x] Video script (each individual)
- [x] Video overall recording
- [x] Video editing
- [ ] Edited user stories
